import Footer from "@/components/Footer";
import Header from "@/components/Header";

export default function About() {
  return (
    <div className="w-[80%] bg-[#f6f6f6] p-3">
      <h1 className="bg-[#1e3c9d] text-white py-2 px-4 font-bold text-xl">
        Ban giám hiệu nhà trường
      </h1>
      <img src="http://yendinh1.edu.vn/uploads/news/2017_07/fb_img_1498371524463.jpg" />
      <p className="mt-4">
      Cùng với sự phát triển và trưởng thành của nhà trường Cấp 3 Yên Định (nay là Trường THPT Yên Định 1) thì Tổ Lý- Hóa – Công nghệ của trường 50 năm qua đã từng bước trưởng thành và góp phần đáng ghi nhận vào thành tích chung của trường.Từ những ngày đầu, trong những năm chiến tranh nhà trường phải sơ tán đóng tại nhiều địa bàn trong huyện, tổ gặp không ít những khó khăn: cơ sở vật chất nghèo nàn, không có phòng thí nghiệm và thực hành, không thư viện, giáo viên lại thiếu…Nhiệm vụ rất nặng nề song cũng thật tự hào, đội ngũ giáo viên trong tổ từ mọi miền quê tụ họp về ngôi trường, cùng nhau vượt qua khó khăn, thiếu thốn, đem sức lực và trí tuệ của mình để dạy dỗ đàn em và xây dựng mái trường ngày càng phát triển trên quê hương Yên Định.
Tổ Lý – Hóa – Công nghệ là tổ có truyền thống đoàn kết, có người mới ra trường, có người thâm niên công tác gần 40 năm nên có tính kế thừa và nối tiếp giữa các thế hệ, song tất cả vẫn thương yêu, giúp đỡ nhau về mọi mặt cả chuyên môn lẫn đức độ làm thầy. Trong sinh hoạt tổ thường xuyên được coi trọng các vấn đề: Rèn luyện đạo đức tác phong người thầy, thường xuyên tự học để không ngừng năng cao trình độ chuyên môn nghiệp vụ, góp ý kiến với nhau chân thành, thẳng thắn để hoàn thành nhiệm vụ được giao. Tổ tích cực tham gia các hoạt động của nhà trường. Vì vậy, nhiều năm liên tục, tổ Lý – Hóa – Công nghệ đều  đạt là tổ lao động tiên tiến xuất sắc. Các thành viên trong tổ đều được đồng nghiệp và các thế hệ học sinh yêu mến, kính trọng.
Trải qua các giai đoạn dù khó khăn hay thuận lợi, tổ Lý – Hóa – Công nghệ vẫn luôn tích cực đẩy mạnh công tác tự nghiên cứu khoa học, đẩy mạnh phong trào làm đồ dùng dạy học, viết sáng kiến kinh nghiệm nhiệt tình vượt qua khó khăn về cơ sở vật chất. Tổ Lý – Hóa – Công nghệ đã có nhiều sáng kiến kinh nghiệm loại A, B, C cấp Tỉnh có hiệu quả áp dụng cao vào công tác giảng dạy. Trong công tác giảng dạy các thầy cô giáo luôn tận tụy, say mê, nhiệt tình với tinh thần “Tất cả vì học sinh thân yêu”. Tổ luôn được Ban giám hiệu Nhà trường và các thế hệ học sinh đánh giá cao về công tác phụ đạo học sinh yếu kém, bồi dưỡng học sinh khá giỏi, học sinh đỗ vào các trường Đại học, Cao đẳng với điểm số cao. Trong đó có các thầy cô giáo ngày đêm miệt mài, thầm lặng đóng góp sức mình vào thành tích đó như: thầy Lê Mạnh, thầy Lê Lân, thầy Trịnh Văn Thơ, thầy Nguyễn Văn Thiệu (là thương binh từ chiến trường trở về), cô Phạm Thị Nga, cô Nguyễn Thị Nhiên, thầy Hà Văn Độ, thầy Nguyễn Đức Hải, thầy Trịnh Văn Thuyên, thầy Trịnh Ngọc Long, thầy Vũ Xuân Thìn…Có nhiều thầy cô giáo được công nhận là giáo viên gỏi cấp tỉnh như: thầy Hà Văn Độ, thầy Nguyễn Đức Hải, thầy Trịnh Văn Thuyên, thầy Vũ Xuân Thìn, thầy Trịnh Ngọc Long…
Tổ Lý – Hóa – Công nghệ rất tự hào vì đã có nhiều thầy cô giáo trưởng thành nhanh chóng, làm công tác quản lí có cơ hội đóng góp nhiều cho sự nghiệp giáo dục như: thầy Phùng Văn Đệ (Nguyên là hiệu trưởng các trường THPT Nguyễn Quán Nho, Dương Đình Nghệ, Thiệu Hóa), thầy Mạch Quang Đắc (Nguyên phó hiệu trưởng trường THPT Yên Định I), thầy Nguyễn Đức Hải (Hiệu trưởng trường THPT Yên Định I), thầy Trịnh Ngọc Long (Phó hiệu trưởng trường THPT Yên Định I).
Hiện nay, tổ Lý – Hóa – Công nghệ có 12 thành viên, tiếp tục phát huy truyền thống, thành tích đã đạt được và trở thành một tổ xung kích trong công tác giảng dạy và các phong trào thi đua của nhà trường. Tổ đã có phòng học bộ môn hiện đại, phòng sinh hoạt chuyên môn, phong trào làm đồ dùng dạy học, viết sáng kiếm kinh nghiệm, phong trào tự học, tự bồi dưỡng luôn được thực hiện với tình thần cao, không ngừng vươn lên nắm bắt kiến thức, khoa học công nghệ mới, đổi mới phương pháp giảng dạy. Thực hiện với tinh thần “Dù khó khăn đến đâu cũng phải thi đua dạy tốt, học tốt”.  Nhiều năm tổ có thành tích nổi bật trong công tác bồi dưỡng học sinh giỏi và học sinh đạt điểm cao thi ĐHCĐ như:
+ Môn Hóa bồi dưỡng học sinh giỏi cấp tỉnh nhiều năm đạt 100% giải: năm học 2007-2008 đạt 1 giải nhất, 4 giải nhì, 4 giải ba và 1 giải KK; năm học 2008-2009 đạt 2 giải nhất, 8 giải nhì.
+ Môn Lý bồi dưỡng học sinh giỏi cấp tỉnh nhiều năm đạt giải cao: năm học 2009-2010 đạt 1 giải nhất, 3 giải nhì, 2 giải ba và 2 giải KK; năm học 2010-2011 đạt 1 giải nhất, 3 giải ba và 5 giải KK.
Nhiều năm nhóm Lý, Hóa có thủ khoa các trường ĐH, trong đó kể đến Thủ khoa Hà Quang Trung (2005) đạt điểm tuyệt đối 30/30 điểm, Thủ khoa Nguyễn Văn Hoàng (2010) là một trong những thủ khoa xuất sắc nhất cả nước được tiếp kiến Chủ tịch nước; Thủ khoa Lê Văn Tùng (2013); Thủ khoa và á khoa Trần Quốc Tuấn (2014). Trong những năm qua có nhiều em sinh thi đại học đạt điểm 10/10 môn hóa, lý. Đóng góp cho trường nhiều thủ khoa Đại học như thầy dạy Lý như: Nguyễn Minh Thiệu, Nguyễn Đức Hải, Trịnh Ngọc Long...Các thầy dạy Hóa như thầy: Lê Lân, Hà Độ, Trịnh Văn Thuyên... 
Nhìn lại một chặng đường 50 năm đã qua, cùng với với những thành quả đã được ghi nhận, còn có rất nhiều những cống hiến thầm lặng của nhiều thầy cô giáo trong tổ. Những công hiến đó được tạo nên từ sự hi sinh vượt khó, xuất phát từ ý thức trách nhiệm và tình yêu thương học trò của mỗi thầy cô giáo. Đó là những cống hiến chưa được tổng kết và cũng khó lòng để nói cho hết, nhưng là phần không nhỏ để tạo nên bề dày truyền thống, sự lớn mạnh của tổ Lý – Hóa – Công nghệ nói riêng và sự nghiệp giáo dục chung của Nhà trường.
Bài học lớn nhất của tổ là đoàn kết, thống nhất, thương yêu giúp đỡ nhau chân thành, không ngừng rèn luyện đạo đức và chuyên môn… Có biết bao điều chúng tôi còn muốn nói về đồng nghiệp thân yêu, về các thế hệ học trò … trong phạm vi của cuốn kỷ yếu bài viết là lời tri ân với đồng nghiệp, với bao thế hệ học trò đã sát cánh bên chúng tôi trong hành trình đã qua, chấp cánh cho tổ Lý – Hóa – Công nghệ hôm nay thêm vững tin tiếp tục truyền thống, vững bước đi lên góp sức mình xây dựng mái Trường THPT Yên Định I mãi mãi là niềm tự hào của bao thế hệ học trò.
      </p>
    </div>
  );
}
