import Footer from "@/components/Footer";
import Header from "@/components/Header";

export default function About() {
  return (
    <div className="w-[80%] bg-[#f6f6f6] p-3">
      <h1 className="bg-[#1e3c9d] text-white py-2 px-4 font-bold text-xl">
        Ban giám hiệu nhà trường
      </h1>
      <img src="http://yendinh1.edu.vn/uploads/hinh_anh_gv/20.jpg" />
      <p className="mt-4">
      Ngay sau khi được thành lập trường, năm học đầu tiên 1965-1966 trường có 6 lớp, tổng số giáo viên của trường chỉ có 15 thầy cô giáo nhưng vấn đề ổn định tổ chức, bộ máy hoạt động được nhà trường và chính quyền các cấp coi trọng; trong đó thành lập Chi bộ đảng nhà trường là một trong những nhiệm vụ cấp bách đặt lên hàng đầu.
          Ngày 05/11/1965, Chi bộ Đảng đầu tiên của nhà trường được thành lập gồm 05 đồng chí: Nguyễn Bá Thiều, Nguyễn Công Hòa, Nguyễn Đình Lân, Phạm Xuân Thông và đồng chí Đào Ngọc Tảo. Trong đó Chi bộ do đồng chí Nguyễn Bá Thiều làm Bí thư. Những năm đầu trải qua bao vất vả, gian nan, dưới làn mưa bom, bão đạn ác liệt của Đế quốc Mỹ với nhiều lần trường chuyển địa điểm. Nhưng với đường lối đúng đắn của Chi bộ, các thế hệ học sinh và đội ngũ cán bộ giáo viên nhà trường kế tiếp nhau thi đua “Dạy tốt - Học tốt - Rèn luyện tốt” nhằm khẳng định truyền thống từng bước trên mỗi chặng đường của trường.
50 năm trôi qua từ những lũy tranh, tre, nứa, lá; lớp học mượn tạm đình làng, nhà dân đến ngói hóa và nay là nhà cao tầng có đủ các điều kiện, phương tiện phục vụ giảng dạy, học tập với môi trường sư phạm “Xanh - Sạch - Đẹp”; nhà trường không ngừng lớn mạnh, chất lượng giáo dục của nhà trường không ngững được nâng lên, trước hết phải nói đến vai trò của Chi bộ (nay là Đảng bộ) là hạt nhân lãnh đạo toàn diện nhà trường.
Những ngày đầu xây dựng trường, đảng viên ít, mỗi đồng chí phải phụ trách nhiều phần việc nhưng nhà trường đều hoàn thành xuất sắc mọi nhiệm vụ: vừa dựng lán lớp, vừa đào hào, đắp lũy để đảm bảo an toàn cho thầy và trò trước những trận bắn phá điên cuồng của Đế quốc Mỹ. Tất cả thầy và trò lúc bấy giờ vừa giảng dạy học tập hăng say vừa tham gia chiến đấu dũng cảm; hàng trăm cán bộ giáo viên nhân viên và học sinh theo tiếng gọi của Tổ Quốc đã lên đường ra trận chiến đấu để bảo vệ miền Bắc xã hội chủ nghĩa, giải phóng miền Nam. Kết thúc cuộc kháng chiến chống Mỹ có hàng chục anh chị không bao giờ trở lại, hàng trăm anh chị bỏ lại một phần xương máu tại chiến trường trong số đó có cả các thầy đã công tác tại trường.
Ngay sau ngày miền Nam được hoàn toàn giải phóng 30 tháng 4 năm 1975, Chi bộ đảng nhà trường tiếp tục chỉ đạo xây dựng chiến lược mới với những khó khăn và thách thức mới. Vào những năm của thập niên 80, lúc này hoàn cảnh kinh tế rất khó khăn, Nhà nước xóa bỏ bao cấp, đời sống cán bộ giáo viên nhân viên khá chật vật, chúng ta hẳn chưa quên những bữa ăn toàn mạch, sắn khô tự giã…Trong bộn bề khó khăn ấy, Chi bộ nhà trường đã thể hiện được vai trò lãnh đạo toàn diện, quyết tâm vượt qua chặng đường tưởng như không khắc phục nổi để tiến lên, thực hiện có hiệu quả phong trào thi đua “Dạy tốt - Học tốt”, phấn đấu hoàn thành mọi nhiệm vụ. Ngoài ra các thầy, cô giáo còn tham gia lao động trồng lúa, chăn nuôi, đóng gạch, vét mương, bốc than… gây quỹ để xây dựng cơ sở vật chất và ổn định đời sống CB,GV, NV.
Trong những năm đầu của thời kỳ đổi mới, sĩ số học sinh thi tăng nhanh. Cũng vào thời kỳ này, cơ sở vật chất của trường đã xuống cấp. Tường rào thấp, phòng học quá thời hạn đã dột nát, bàn ghế hư hỏng, học sinh phải ngồi xuống ghế xi măng. Ban giám hiệu, đảng ủy lúc bấy giờ tiếp tục tham mưu với chính quyền các cấp để được đầu tư cơ sở vật chất. Năm 1996, nhà trường được đầu tư xây dựng trường 2 tầng gồm 14 phòng học. Năm 2000 nhà hiệu bộ chính thức đi vào sử dụng, cơ sở vật chất tuy còn thiếu nhưng đã phục vụ được giảng dạy và học tập của giáo viên ở mức khá hơn. Lúc này quy mô đào tạo của trường lớn mạnh, cơ sở vật chất khang trang, điều kiện kinh tế xã hội trên địa bàn cũng phát triển tốt hơn.
Cũng vào thời điểm này, Chi bộ đã có những Nghị quyết chuyên đề hết sức đúng đắn để chỉ đạo, lãnh đạo nhà trường thích ứng với tình hình mới của đất nước. Có thể nói rằng giai đoạn này Trường THPT Yên Định 1 đã có sự chuyển mình, tiến bộ nhanh chóng về mọi mặt: số lượng học sinh tăng nhanh, chất lượng được duy trì tốt, phong trào thi đua dạy giỏi, học giỏi diễn ra sôi nổi. Đây chính là động lực nâng cao chất lượng giáo dục toàn diện. Tỷ lệ học sinh xếp loại đạo đức khá, tốt hàng năm trên 95%, tỷ lệ lên lớp thẳng 99%, đỗ tốt nghiệp hàng năm đều vượt chỉ tiêu đặt ra, có nhiều học sinh đạt giải quốc gia và giải học sinh giỏi cấp tỉnh.
Bước sang năm học 2004-2005, Đảng ủy, Ban giám hiệu lại tập trung chỉ đạo công tác chuẩn bị tốt cho lễ kỷ niệm 40 năm ngày thành lập trường (1965-2005).
Tháng 11 năm 2005, lễ kỷ niệm 40 năm thành lập trường được tổ chức long trọng. Lần đầu tiên các thế hệ các thầy và học trò về tụ họp tương đối đông đủ. Phong trào xã hội hóa giáo dục được khơi dậy; các thế hệ học sinh cũ của trường nay đã thành đạt, góp kinh phí tăng cường cơ sở vật chất cho nhà trường. Lúc này cấp ủy, ban giám hiệu tiếp tục tham mưu với chính quyền các cấp để trường được đầu tư cơ sở vật chất, các dãy nhà cao tầng dần được thay thế cho các dãy nhà cấp 4 đã xuống cấp, trang thiết bị tiếp tục được đầu tư theo hướng hiện đại, chất lượng dạy và học nhà không ngừng được nâng lên.
Đại hội Chi bộ nhiệm kỳ 2010-2015 đã đề ra Nghị quyết cho giai đoạn mới của trường là nâng cao chất lượng giữ vững trong tốp đầu các trường trong tỉnh, nhanh chóng xây dựng trường THPT Yên Định 1 thành trường THPT đạt chuẩn Quốc gia và phấn đấu năm 2015 sẽ được Nhà nước trao tặng Huân chương Lao động hạng nhất. Nghị quyết xây dựng trường THPT Yên Định 1 thành trường chuẩn Quốc gia được đông đảo cán bộ, đảng viên tán thành, quần chúng hưởng ứng quyết tâm thực hiện. Kế hoạch xây dựng trường chuẩn được đưa vào từng năm học, từng học kỳ, từng tháng và hàng tuần. Chi bộ, Ban giám hiệu thường xuyên kiểm tra rà soát các tiêu chuẩn để nhanh chóng hoàn thành các tiêu chí. Tháng 6/2012 trường THPT Yên Định 1 được công nhận là trường chuẩn Quốc gia, là trường đầu tiên trong huyện và là trường THPT thứ 13 trong tỉnh đạt chuẩn Quốc gia.
Tháng 7 năm 2012 trước nhiệm vụ chính trị trong giai đoạn mới của trường và sự phát triển số lượng Đảng viên, ngày 10 tháng 7 năm 2012, Huyện ủy Yên Định có Quyết định số 274-QĐ/HU thành lập Đảng bộ trường THPT Yên Định 1 trên cơ sở Chi bộ trường THPT Yên Định 1 trước đây. Hiện nay, nhà trường có Đảng bộ với 47 Đảng viên, chiếm tỷ lệ 68% số cán bộ giáo viên trong đơn vị. Đảng bộ trường THPT Yên Định 1 có 3 chi bộ trực thuộc, là hạt nhân tiên phong trong các phong trào thi đua dạy tốt, học tốt. Đảng bộ thực sự là hạt nhân chính trị, lãnh đạo toàn diện các hoạt động của nhà trường.
Cấp ủy, Ban giám hiệu đã chỉ đạo tốt việc phân công chủ nhiệm lớp, phân công giảng dạy và việc phân các ban đối với học sinh; phân công lao động đúng người, đúng việc phát huy hết mọi khả năng của bản thân để nâng cao kết quả dạy và học. Số giáo viên giỏi ngày một tăng, nhiều năm liên tục trường có thủ khoa các trường Đại học, trong đó có những thủ khoa xuất sắc nhất của cả nước như thủ khoa được tiếp kiến Chủ tịch nước, thủ khoa được các kênh truyền hình, đài tiếng nói Việt Nam ca ngợi.
Trong những năm qua Cấp ủy tập trung chỉ đạo các tổ chức trong nhà trường như công đoàn, đoàn thanh niên, tổ chuyên môn. Xây dựng ngồn cán bộ đảm bảo sự kế thừa và phát triển, đặc biệt quan tâm đến xây dựng sự đoàn kết nội bộ và xây dựng cơ quan văn hóa, từng bước nâng cao đời sống, văn hóa tinh thần cho cán bộ giáo viên. Nhiều phong trào văn hóa văn nghệ, thể dục thể thao được quan tâm.
Trong những năm qua, Đảng bộ liên tục đạt danh hiệu đảng bộ trong sạch vững mạnh, 100% đảng viên đều hoàn thành tốt và hoàn thành xuất sắc nhiệm vụ. Đảng bộ nhà trường luôn được Đảng bộ huyện Yên Định và Đảng bộ tỉnh Thanh Hóa khen thưởng.
          - Năm 2010 được Đảng bộ Huyện Yên Định tặng danh hiệu đơn vị xuất sắc toàn diện trong quá trính 10 năm xây dựng Huyện anh hùng 2000-2010.
          - Năm 2011 được Tỉnh ủy Thanh Hóa tặng bằng khen“Chi bộ trong sạch vững mạnh, tiêu biểu 3 năm 2008-2010”. Huyện ủy Yên Định tặng danh hiệu đơn vị xuất sắc dẫn đầu trong cuộc vận động “Học tập và làm theo tấm gương đạo đức Hồ Chí Minh”
          - Năm 2012 có 01 đồng chí trong Đảng bộ được Tỉnh ủy tặng Bằng khen và 01 đồng chí đạt giải ba; 01 đồng chí giải khuyến khích cấp tỉnh về cuộc thi “Bác Hồ với Thanh Hóa, Thanh Hóa làm theo lời Bác dạy”.
          - Đặc biệt, năm 2014 Đảng bộ nhà trường được Tỉnh ủy tặng Bằng khen“Đảng bộ trong sạch vững mạnh, tiêu biểu 3 năm 2010-2013”
          Nhìn lại 50 năm qua, công tác Đảng trong trường THPT Yên Định 1 đã để lại những bài học rất quí báu, đó là bài học về hạt nhân lãnh đạo toàn diện, giữ vững sự đoàn kết thống nhất trong mỗi Chi bộ, Đảng bộ như “Giữ gìn con ngươi của mắt mình”; giữ nghiêm kỷ luật của Đảng; thực hiện tốt nguyên tắc tập trung dân chủ, tập thể lãnh đạo, cá nhân phụ trách; phát huy cao độ tính tiền phong gương mẫu của cán bộ, đảng viên trong mọi lĩnh vực công tác; vận dụng đúng đắn, sáng tạo, nhanh nhạy chủ trương đường lối, Nghị quyết của Đảng; Pháp luật của Nhà nước vào sự nghiệp giáo dục nói chung, của nhà trường trong mỗi học kỳ, mỗi năm học.
          Thành tích mà trường giành được trong suốt 50 năm qua là rất đáng phấn khởi, là niềm tin của tất cả các thế hệ thầy, cô và học sinh nhà trường. Song so với yêu cầu của Nghị quyết 29 của BCH TW (khóa XI) về “Đổi mới căn bản, toàn diện Giáo dục và Đào tạo đáp ứng yêu cầu CNH - HĐH trong điều kiện kinh tế thị trường định hướng XHCN và hội nhập Quốc tế” thì những thành quả đã đạt được mới chỉ là bước đầu. Vì vậy, Đảng bộ cần chỉ đạo, lãnh đạo tốt công tác xây dựng và phát triển nhà trường trong giai đoạn mới nhất là giai đoạn 2015-2020 và những năm tiếp theo.

Nguyễn Đức Hải - Bí thư Đảng bộ
      </p>
    </div>
  );
}
