import Footer from "@/components/Footer";
import Header from "@/components/Header";

export default function About() {
  return (
    <div className="w-[80%] bg-[#f6f6f6] p-3">
      <h1 className="bg-[#1e3c9d] text-white py-2 px-4 font-bold text-xl">
        Ban giám hiệu nhà trường
      </h1>
      <img src="/images/1237.jpg" />
      <p className="mt-4">
      Để hoạt động công đoàn thực sự đi vào chất lượng, Công đoàn trường THPT Yên Định 1 đã xây dựng kế hoạch hoạt động trong phối hợp chặt chẽ, gắn bó với chuyên môn. Với ý thức cùng với chuyên môn thúc đẩy chất lượng giảng dạy, nâng cao hiệu quả đào tạo học sinh giỏi đã giúp hoạt động Công đoàn ngày càng phù hợp với môi trường giáo dục của nhà trường. Công đoàn trường đã tổ chức phát động nhiều phong trào thi đua trong CBGV, công đoàn viên, trọng tâm là phong trào thi đua “Hai tốt”, “Lao động giỏi, lao động sáng tạo”, phong trào “Giỏi việc trường, đảm việc nhà”, phong trào “Học tập và làm theo tấm gương đạo đức Hồ Chí Minh”... gắn các phong trào này với các cuộc vận động lớn của ngành do cấp uỷ Đảng, chính quyền phát động “Dân chủ, kỉ cương, tình thương, trách nhiệm”, cuộc vận động “Hai không” với 4 nội dung; cuộc vận động “Mỗi thầy cô giáo là một tấm gương đạo đức tự học và sáng tạo”... Công đoàn đã thường xuyên làm tốt công tác tuyên truyền nâng cao nhận thức chính trị tư tưởng cho đoàn viên công đoàn. Để trường THPT Yên Định 1 luôn là một trong những trường dẫn đầu trong toàn tỉnh, Công đoàn trường luôn coi trọng xây dựng và nâng cao chất lượng đội ngũ nhà giáo về đạo đức, về chuyên môn.
          Trên cơ sở thi đua “Dạy tốt, học tốt”, “Đổi mới công tác quản lí giáo dục, nâng cao chất lượng giáo dục”. Công đoàn cùng với chuyên môn làm tốt công tác bồi dưỡng chuyên môn cho giáo viên. Công đoàn Nhà trường còn chủ động phối hợp cùng với chuyên môn bàn biện pháp tháo gỡ khó khăn để duy trì nâng cao chất lượng đào tạo của nhà trường ở cả hai phương diện giáo dục toàn diện và giáo dục mũi nhọn. Công tác viết SKKN được đông đảo CBGV tham gia và đã có nhiều đồng chí có SKKN xếp loại cấp ngành, xếp loại cấp tỉnh như thầy Nam, thầy Hải, thầy Hiển... các thầy cô nhiều tuổi bồi dưỡng học sinh giỏi có nhiều giải cao như thầy Bách hai lần có học sinh giỏi Quốc gia; các thầy Tuyến, thầy Thắng, thầy Nhẫn, thầy Thiệu, thầy Lân, thầy Nhân, thầy Chính, thầy Hưng ... có nhiều học sinh đạt giải Nhất, Nhì cấp tỉnh. Các thầy cô trẻ tuổi hiện nay phát huy truyền thống của nhà trường viết tiếp trang sử vẻ vang như thầy Nguyên, thầy Hùng, thầy Thuyên, thầy Long, cô Tiên, cô Hoa, cô Vân, cô Hà, cô Thủy... các thầy cô tiếp tục bồi dưỡng HSG mang lại thành tích cao cho nhà trường, bên cạnh đó việc ôn thi đại học đã mang lại kết quả rất đáng tự hào đó là nhiều năm nhà trường có học sinh đậu thủ khoa, á khoa các trường đại học lớn với điểm số rất cao, có học sinh đạt điểm tuyệt đối 30/30. Các thầy có học sinh đậu thủ khoa các trường đại học như thầy thầy Thắng, thầy Thiệu, thầy Lân, thầy Hải, thầy Hiển, thầy Tài, thầy Long, thầy Thuyên, thầy Hùng…
          Bên cạnh đó, công tác chăm lo đời sống cho CBGV, NV nhà trường được Công đoàn nhà trường đặc biệt quan tâm. Những chuyến du lịch, tham quan học tập kinh nghiệm ở các tỉnh thành phía Bắc như Hạ Long, Cát Bà, Móng Cái, Sa Pa, Hà Khẩu (Trung Quốc); các chuyến vào miền Trung như Huế, Quãng Bình hay các chuyến vào Nam  đến Vũng Tàu, TP Hồ Chí Minh, Đà Lạt, Nha Trang... còn in đậm trong mỗi các nhân đoàn viên công đoàn. Để thực hiện được các chuyến đi thực tế, ý nghĩa này không thể không nhắc đến sự tích cực nhiệt tình của BCH Công đoàn các thời kỳ trong đó phải kể đến vai trò của các đồng chí Chủ tịch Công đoàn như các thầu Lê Trọng Hòa, Nguyễn Hữu Tứ, Trịnh Trọng Nam, Nguyễn Đức Hải, Lê Văn Hiển...

          Trong 50 năm qua đã có hơn 300 CBGV, NV đã công tác ở mái trường này, những người ươm mầm cho tương lai đã tung cánh bay đi khắp muôn phương, nhiều thầy cô đã phấn đấu trở thành giáo sư, tiến sĩ, thạc sĩ, cán bộ giảng dạy ở các trường đại học như thầy Lê Huy Trâm, Lê Cương, Lê Như Bình... Trong đội ngũ hơn 70 thầy cô hiện nay có nhiều thầy cô gần như gắn trọn đời với mái trường này, có thầy cô mới ra trường, các thế hệ các thầy cô giáo sẽ tiếp tục có những cuộc bàn giao lịch sử để viết tiếp trang sử vẻ vang của nhà trường, xây dựng tổ ấm Công đoàn trường THPT Yên Định 1 luôn ấm áp và tràn đầy tình thương.
          Trong năm thập kỷ qua, Công đoàn trường THPT Yên Định 1 đã vinh dự được tặng 30 giấy khen của Công đoàn ngành, 7 bằng khen của Liên đoàn Lao động tỉnh Thanh Hóa, 01 cờ "Đơn vị dẫn đầu phong trào thi đua" của Liên đoàn Lao động tỉnh Thanh Hóa,  4 bằng khen của Công đoàn ngành Giáo dục Việt Nam, 3 bằng khen của Tổng Liên đoàn Lao động Việt Nam. Có hàng trăm lượt giáo viên đạt giáo viên giỏi cấp huyện, cấp cụm, hàng trăm lượt giáo viên đạt danh hiệu CSTĐCS, trên 20 lượt giáo viên đạt danh hiệu thi đua CSTĐ cấp tỉnh, trên 40 lượt giáo viên được tặng bằng khen của các cấp, hàng chục CBGV được tặng thưởng Huân chương Lao động các hạng.
          Nửa thế kỷ xây dựng và phát triển nhà trường là khoảng thời gian chưa dài với sự phát triển của xã hội nhưng đó là thời gian đủ lớn so với cuộc đời của mỗi nhà giáo, được sinh hoạt trong tổ chức công đoàn và được giảng dạy ở một ngôi trường có bề dày truyền thống như vậy, là niềm vinh dự và tự hào của mỗi người, bởi trong thành tích chung của nhà trường có sự chung tay góp sức của mỗi thành viên trong tổ chức Công đoàn. Công đoàn trường THPT Yên Định 1 sẽ nối vòng tay lớn, vững vàng đi lên xây dựng nhà trường tiếp tục phát triển góp phần vào sự nghiệp trồng người cho quê hương Yên Định anh hùng.
 
      </p>
    </div>
  );
}
